[project]
name = "proj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.6",
    "pandas>=2.3.2",
    "py-cpuinfo>=9.0.0",
    "seaborn>=0.13.2",
    "tensorflow>=2.20.0",
]
